linters:
  enable:
    - gocritic
    - gosec
    - gofmt
    - goimports
    - gocyclo
    - goconst
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  gosimple:
    go: "1.18"
  gocyclo:
    min-complexity: 15
