# TODO: remove this section once all linters support go 1.18
run:
  go: "1.17"

linters:
  enable:
    - gocritic
    - gosec
    - gofmt
    - goimports
    - gocyclo
    - goconst
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
